### ISSUE TITLE
Failure to launch live-desktop

### ISSUE THREAD

**Issue by nsgnn** [clearlinux/clr-installer#484]
Machine is already running a clear linux install, but I cannot launch a live-desktop version of clear linux due to `failing to find installer media...` My main disk is encrpyted with luks, but beyond that it is the same hardware as when I previously installed clear linux using a live desktop image. The image is fresh off the website though. I followed the "create a boot usb" tutorial on the clear linux site.

![Error screenshot](https://user-images.githubusercontent.com/978752/62055931-374c8e00-b1e2-11e9-8948-c099c9394c33.png)

**Comment by mdhorn** [comment]
The problem appears to be in the recent releases of Clear Linux. 
The initrd process is not able to find the installer media likely due to a recent kernel change in the distribution. 
The problem is under investigation.

**Comment by miguelinux** [comment]
@mdhorn is the same for the CLEAR-4703

**Comment by mdhorn** [comment]
Fixed in release 2.1.1  which should land in Clear Linux* OS release > 30610

**Comment by nsgnn** [comment]
This issue persisted with version 30650 on host machine and usb version(the one failing to boot to live-desktop).

**Comment by mdhorn** [comment]
@nsgnn The fix is was how the ISO image was created; not in the host OS.
I just download and boot the 30650 ISO image in qemu
`qemu-system-x86_64 -enable-kvm -cpu host -smp 4 -m 1024 -cdrom clear-30650-live-server.iso`

If this image is not booting for you, please provide the full command you are using or verify the checksum on the download ISO.

**Comment by EdPhere** [comment]
I'm getting the Failed to find installer media when booting the iso which was downloaded from here.  I've tried every bootparm I know of to get it to recognize the iso.

Grub2Win menu

menuentry " Clear Linux* OS"   --class other --class icon-gnugrub  {

     set lang="en" 
     set iso="/Users/Ed/Downloads/clear-32270-live-desktop.iso"
     set bootparms="from=all, from=$iso, fromiso=$iso, findiso=$iso, iso-scan/filename=$iso, bootfrom=/dev/sda6$iso    qemu-system-x86_64 -enable-kvm -cpu host -smp 4 -m 1024 -cdrom $iso"

     set bootdrv=$root
     search -f $iso --set=root 
     if [ $? = 0 ] ; then
        loopback loop $iso
        linux  (loop)/kernel/kernel.xz $bootparms
        initrd (loop)/EFI/BOOT/initrd.gz 
        loopback --delete loop
     else
        echo "----------------------------------------"
        echo ISO NOT found. root=$root bootdrv=$bootdrv
        echo $iso
        echo
        sleep -v -i 10
     fi
     set root=$bootdrv
     }

**Comment by EdPhere** [comment]
Oops!!  lol

     set bootparms="from=all, from=$iso, fromiso=$iso, findiso=$iso, iso-scan/filename=$iso, bootfrom=/dev/sda6$iso quiet console=tty0 console=ttyS0,115200n8 cryptomgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcu_nocbs=0-64 rcupdate.rcu_expedited=1 tsc=reliable rw rootwait" # rootfstype=ext4,btrfs,xfs "

**Comment by EdPhere** [comment]
Restarted problem here: https://github.com/clearlinux/clr-installer/issues/669
